version: '3.8'
services:
    flask:
        build: ./flask
        container_name: flask
        restart: always
        environment:
            - APP_NAME=Flask
        volumes:
            - .:/flask
        entrypoint: python3
        command: run.py
        # command: uwsgi /flask/flask/uwsgi.ini
        ports:
            - "5000:5000"
        expose:
            - 5000

    marblecutter-virtual:
        build: ./marblecutter-virtual
        container_name: marblecutter-virtual
        environment:
            - PYTHONPATH=.
        volumes:
            - .:/opt/marblecutter/marblecutter-virtual/
        restart: unless-stopped
        entrypoint: python
        command: server.py
        # command: uwsgi /opt/marblecutter/marblecutter-virtual/uwsgi.ini

        ports:
            - "8000:8000"
        expose:
            - 8000

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        restart: always
        depends_on:
            - flask
            - marblecutter-virtual
        ports:
            - "80:80"

